export const actionType = {
    CHANGE_STATUS_TASK: 'CHANGE_STATUS_TASK',
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    ADD_ALL_TASKS: 'ADD_ALL_TASKS',

    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    ACTIVE_CATEGORY: 'ACTIVE_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
    ADD_ALL_CATEGORY: 'ADD_ALL_CATEGORY',

    LOGIN: "LOGIN",
    ADD_USER: 'ADD_USER',
    ACTION_LOADER: "ACTION_LOADER",

    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',

    ADD_MODAL: 'ADD_MODAL',
    REMOVE_MODAL: 'REMOVE_MODAL'
};
